### ISSUE TITLE
Documentation of using ES directly

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-enhanced-search#10]
Currently our docs are good for the Posts Search Index, but doesn't go into details on how to use ES directly for advanced things.

**Comment by roborourke** [comment]
We have the function for getting the ES URL documented so far, is that enough or are you thinking like custom faceted search results etc?

**Comment by roborourke** [comment]
We first need to determine a list of what some of these advanced things are then add them as acceptance criteria. Suggestions welcome!

**Comment by joehoyle** [comment]
I don't think we need to document actual advanced things, we need to document how to send arbitrary queries and get arbitrary results back from ES

**Comment by roborourke** [comment]
This was done in #21
