### ISSUE TITLE
Search config under settings?

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-enhanced-search#102]
It seems quite strange to me to see Search Config as a top-level page in the admin menu:

<img width="173" alt="Screen Shot 2020-09-16 at 12 03 05" src="https://user-images.githubusercontent.com/21655/93329110-9b7e4700-f814-11ea-9881-cb0597721dcb.png">

IMO, the configuration part at least should be under Settings, as they're mostly set-and-forget settings.

"Custom Search Results" is a bit different, but also doesn't seem important enough (IMO) to take up an entry at the top level of the hierarchy. Either another entry under Settings or perhaps under Tools?

(Also, not sure how the permissions here work)

**Comment by joehoyle** [comment]
Oh, yeah I just came here to create the exact same ticket :D IMO this should be pre-v5 release else we are moving a new thing around

**Comment by rmccue** [comment]
Well, we shipped this and no one has complained; we can revisit in the future.
