### ISSUE TITLE
ElasticPress v3 API endpoint has warnings

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-enhanced-search#114]
Steps to reproduce:
1. Go to a post edit page
2. Query monitor shows 2 warnings for missing permission_callbacks in the customised search results endpoint

There should be no PHP warnings.

Possible approaches:

- Best is to get the latest version of EP if there's a fix upstream
- Try to patch upstream if not

There's another approach using composer patches but that's a bigger topic.

Acceptance criteria:

- [ ] No REST API warnings

**Comment by joehoyle** [comment]
Ran into this in https://github.com/humanmade/marketing-sites/issues/894 too

**Comment by roborourke** [comment]
Going to speak to Taylor Lovett but it seems the most practical and surefire way of dealing with this right now is to add our fork of ElasticPress to packagist and backport the changes ourselves. Not ideal but does give us some control over a key dependency.

**Comment by mcshanea** [comment]
Depended on conversation with 10up relating to backporting fixes.

**Comment by roborourke** [comment]
I think this ship has sailed really, it’s fixed in the latest versions of Altis and is a benign issue. Closing out
