### ISSUE TITLE
Upgrade to ElasticPress 3.5

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-enhanced-search#117]
> Version 3.5 is a very exciting release as it contains two major new features: a synonym dashboard and search term result highlighting. The synonym dashboard empowerers users to create synonym lists for searches. For example. searching "New York City" would return contain with "NYC". Search term highlighting will underline and add a CSS class to keywords within content that matches the current search.
> 
> The new version also includes a revamp of the search algorithm. This is a backwards compatibility break. If you'd like to revert to the old search algorithm, you can use the following code: add_filter( 'ep_search_algorithm_version', '3.4' );. The new algorithm offers much more relevant search results and removes fuzziness which results in mostly unwanted results for most people. If you are hooking in and modifying the search query directly, it's possible this code might break and you might need to tweak it.

We're already making big changes to the default search query, and them removing fuzziness when we've just gone to some lengths to improve it and provide control over it means we need to carefully compare the changes and possibly keep to the old search algorithm version.

Acceptance criteria:

- [ ] Synonyms dashboard is hidden (we're using AWS Elasticsearch Service packages for this)
- [ ] Search continues to work:
   - On the front end
   - In the admin
   - In the media library (using autosuggest typeahead)
- [ ] Indexing still works
- [ ] Custom packages still work
- [ ] Our custom analysers still get added and used
- [ ] Local server setup & index creation still works

**Comment by goldenapples** [comment]
Version 3.5 includes permissions callbacks for the REST routes registered by the plugin, to prevent throwing PHP notices in WordPress 5.5.  It'd be good to update on the sooner side so that using the altis-enhanced-search module as part of Altis v5 doesn't throw warnings out of the box.

**Comment by roborourke** [comment]
@goldenapples this won’t be until v6 at least and we have higher priority pieces we’re working on, that said we are talking to 10up about backporting the fix to the 3.4 branch. Will chase that up again next week
