### ISSUE TITLE
Implement autocomplete for Japanese

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-enhanced-search#123]
There's a tutorial here on how to implement this: https://www.elastic.co/blog/implementing-japanese-autocomplete-suggestions-in-elasticsearch

The basic autosuggest we have now won't really account for reading forms and katakana to romaji transformation.

**Comment by rmccue** [comment]
Moved to [Productboard](https://altis.productboard.com/feature-board/2392164-everything-now/features/7895807/detail)
