### ISSUE TITLE
Enhanced Search is not returning correct results on local and platform test

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-enhanced-search#136]
Steps to reproduce:
1. Add some manual synoyms eg. "cat, dog, hamster"
2. Add a post containing only the word cat
3. Add a post containing only the word dog
4. Add a post containing all 3 words
5. Search on the front end (or admin) for "cat", only 2 results are found (the two with the word "cat" in them)

I have confirmed that ElasticSearch is running in `local-server`, has been set up, and has been indexed after updating the search config. No errors appear in Query Monitor.

![Screen Shot 2021-01-14 at 12.53.18 PM.png](https://images.zenhubusercontent.com/5806695a95e42b6c5baaac94/2f0ed101-68f8-4123-81b5-ed7c95d85d53)

![Screen Shot 2021-01-14 at 12.53.35 PM.png](https://images.zenhubusercontent.com/5806695a95e42b6c5baaac94/d7032d03-1bd3-4876-9676-1335c68e59e1)

**Comment by goldenapples** [comment]
Seeing the error `field [post_date_gmt] is of type [org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType@554b40e9], but only numeric types are supported."` is an indication that the mapping hasn't been put correctly before indexing.

You can put the mapping on its own with `wp elasticpress put-mapping` or (I believe) do it as part of indexing with `wp elasticpress index --setup`.

When I've gotten that error, it's been as a result of indexing without putting the mapping first and I've had to delete the index, put the new mapping, and reindex.

**Comment by jazzsequence** [comment]
Thanks @goldenapples 
That does resolve my ElasticSearch local issues. The actual search results remain the same in testing, however, so I will update the description.

**Comment by roborourke** [comment]
On cloud environments you have to re-index the data for changes to synonyms etc to take effect generally, although on platform-test that shouldn't be the case as it's using Elasticsearch 7. I have just seen some general issues relating to this though and reindexing is currently failing, looking into that.

**Comment by roborourke** [comment]
Ok, issue is now resolved on `platform-test`. I had to increase the instance size to a `t3.medium` then add an extra node to get the cluster health status to green. We can jump on a call later to check the local results @jazzsequence. The way it works on local is a bit Rube Goldberg so there's a few points of failure to check.

**Comment by jazzsequence** [comment]
Did some debugging with @roborourke and was able to resolve this after flushing the cache.
