### ISSUE TITLE
Content in reusable blocks is not searched

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-enhanced-search#152]
Steps to reproduce:

1. Insert a paragraph into a post containing some unique text
2. Save the paragraph as a reusable block
3. Publish the post
4. On the front end, search the site for the text
5. Observe there are no results

Reusable blocks can contain content that should be discoverable via search.

This problem is probably something that should be addressed upstream in ElasticPress, but in the meantime and with regard to Altis Enhanced Search we might be able to add the content of reusable blocks to the index when a post is saved. We'd need to consider how to rebuild those indexes when a reusable block is updated.

_Aside: This is probably a wider problem that affects shortcodes and server-side rendered blocks too, but let's focus on reusable blocks here as they're promoted to a top-level feature on Altis._

**Comment by roborourke** [comment]
Yep, by default ElasticPress will search against the indexed `post_content` rather than the `post_content_filtered` field. We can certainly patch this in Altis. If you're in a hurry you can use the `ep_search_fields` filter to replace `post_content` with `post_content_filtered`.
