### ISSUE TITLE
Consider bundling an Elasticsearch GUI

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-enhanced-search#18]
There are few GUIs that are super useful when working with Elasticsearch, either for debugging or for developing queries.

An app like [Cerebro](https://github.com/lmenezes/cerebro ) or Kibana could be made available as part of local-server or the ECS based stacks.

Something like this coupled with easy access to an elasticsearch query log / access logs would remove one of the major pain points of developing on ES.

**Comment by joehoyle** [comment]
We actually have Kibana already available on AWS, so we could provide that.

**Comment by roborourke** [comment]
Local server now has Kibana, so would just be good to provide a link to kibana for the stack now. Thinking that would be something for vantage so we can close this issue

**Comment by mikeselander** [comment]
I know this is a rather ancient issue, but I think that we're missing something important here: even if there is a UI within vantage, I can't find an equivalent for local development. Local is where you're (hopefully) generating the most errors and having a UI to trace these is really important for development. 

I think that this issue should be re-opened and that we should have a consistent UI for debugging Elasticpress errors and logs.

**Comment by rmccue** [comment]
@mikeselander if you're on local-server, I think going to `/kibana/` has the Kibana UI? We also had a ticket/PR open for linking out to that from the admin as well IIRC.

**Comment by mikeselander** [comment]
We're using `local-chassis` because there's some blockers to us using the Docker containers as it is now. Is there an equivalent for Chassis?

**Comment by roborourke** [comment]
There’s a kibana chassis extension but I don’t know if it works out of the box with the elasticsearch extension, presumably it does but I haven’t tested that combination.

**Comment by roborourke** [comment]
FWIW Mike I documented how to get started with Kibana for local server, I could do the same for local chassis. It’s not as bad as it looks at first but you have plenty of other options, for example if you prefer the head browser you can install that as a browser extension and point it to port 9200 on your chassis host.

Saying that if we add a way to browse ES in production it’ll be kibana as AWS provide it out of the box so it’s worth learning IMO. My intention is to put together some workshops / videos discussing these bits in more detail.

**Comment by mikeselander** [comment]
> it’s worth learning IMO

You're not wrong at all and I intend to learn more about it. 

I suppose my biggest issue here is that we're yanking out a pretty usable UI and replacing it with a far-less user-friendly UI in a separate tool and expecting developers (internal and external) to just learn this new tool on top of all the other unique-to-Altis things. I'm not even sure that Kibana will catch everything - iirc Elasticpress catches all queries and it looks like we're just logging errors? Could be wrong here.

**Comment by joehoyle** [comment]
What is the usable UI we are yanking out? Am I missing something obvious? It seems to me the above comment is assuming kibana is some kind of replacement to elasticpress? Or is there some whole part of elasticpress UI I’ve never encountered that’s for viewing data in ES?

--

Joe Hoyle

CTO
Human Made

**Comment by roborourke** [comment]
@mikeselander we added an extension for query monitor that will log all EP queries here https://github.com/humanmade/altis-enhanced-search/pull/56

Does that cover it?

**Comment by mikeselander** [comment]
It helps (quite a bit, I was using this earlier), but what if you need to trace queries in an AJAX, REST, or cron call?

**Comment by roborourke** [comment]
Gotcha, yeah we hid the default UI @joehoyle which I think showed logs. I’ve never actually checked the output of composer server logs elasticsearch!

**Comment by joehoyle** [comment]
Ohhhhh ok, if that is the case, we should bring that back.

This has been a hugely confusing conversation for me! This issue is about providing an _elasticsearch_ GUI, to explore data in elastcisearch. If we are talking about not having the _ElasticPress_ press GUI shown (logs etc) then that makes a lot more sense. Kibana is an answer to the former issue (visualize / explore data in elasticsearch) and nothing to do with ElasticPress, or viewing errors / request logs from ElasticPress. Though, granted this issue did also mention:

> Something like this coupled with easy access to an elasticsearch query log / access logs would remove one of the major pain points of developing on ES.

Which isn't a Kibana issue / concept, so I think maybe that lead to the confusion here.

So, I think we need another ticket for implementing/exposing the ElasticPress Logs UI that apparently comes with the plugin. Though I can imagine we'll also need to see how that stores the logs, as it might not be scalable.

**Comment by mikeselander** [comment]
> This issue is about providing an elasticsearch GUI, to explore data in elastcisearch. If we are talking about not having the ElasticPress press GUI shown (logs etc) then that makes a lot more sense. 

Oh, I definitely did mis-read the intent of this Issue! I'll open another issue for that.
