### ISSUE TITLE
Error in ElasticSearch request on local server

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-enhanced-search#180]
**Note:** This might be a local configuration issue again, but I've tested on two local environments and search is not working on either of them and is broken on Platform Test (see humanmade/platform-test#85).

Steps to reproduce:
1. Add some manual synoyms eg. "cat, dog, hamster"
2. Run `wp elasticpress index`
2. Add a post containing only the word cat
3. Add a post containing only the word dog
4. Add a post containing all 3 words
5. Search on the front end (or admin) for "cat" and check results come back with all 3 posts from above

Expected result:
All relevant posts appear in the search results

![Screen Shot 2021-04-02 at 11 51 11 AM](https://user-images.githubusercontent.com/991511/113440509-cd6a8b80-93a9-11eb-8299-079806ad6654.png)

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
The error to with the post date mapping is weird but the command to reindex should be:

```
wp elasticpress index --setup --network-wide --url=...
```

The `--setup` flag is required for any updates to the mappings.

**Comment by jazzsequence** [comment]
I've run the reindex with the setup flag multiple times with no change.

**Comment by jazzsequence** [comment]
Possibly related:

Attempting to reindex on Platform test returns this error:

```
Warning: Error in ElasticPress request: put_mapping {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"failed to build synonyms"}],"type":"illegal_argument_exception","reason":"failed to build synonyms","caused_by":{"type":"parse_exception","reason":"parse_exception: Invalid synonym rule at line 2","caused_by":{"type":"illegal_argument_exception","reason":"term: dungeons and dragons analyzed to a token (dragon) with position increment != 1 (got: 2)"}}},"status":400} (400) in /usr/src/app/vendor/altis/enhanced-search/inc/namespace.php on line 303
Error: Mapping failed
```
https://dashboard.altis-dxp.com/#/eu-west-1/platform-test/wp-cli

**Comment by roborourke** [comment]
ah that's interesting, not seen a synonym format issue before. I suspect we'd get this same error locally too

**Comment by roborourke** [comment]
Fixed in Elasticsearch 6.6 apparently 🤦  If you remove or change the synonyms to "dungeon and dragon" singular it might work. If it works with the basic examples still then that's something.

**Comment by roborourke** [comment]
ohhhh you know what - I think it's because stopwords are removed first so the "and" is being dropped hence the token "dragon" is expected to be at position (index) 1 and not 2. Might be able to fix that but lets rename this issue to something more specific, or close it in favour of a new specific one.

**Comment by jazzsequence** [comment]
Let me test a couple things based on that ☝️ and I'll update the title & description.

**Comment by jazzsequence** [comment]
Okay, yeah, this must've been a result of explicitly including "and" in the synonym phrase "dungeons and dragons".  Updating it to `dungeons, dragons, dnd, d&d, dungeons & dragons` returned expected results:

![Screen Shot 2021-04-06 at 2 27 16 PM](https://user-images.githubusercontent.com/991511/113774262-450b2400-96e4-11eb-8bcb-55e50399b4d4.png)

I'm going to call this an edge case as it seems like it's working now 👍

**Comment by roborourke** [comment]
Thanks for confirming, and for the new issue @jazzsequence 👍
