### ISSUE TITLE
Synonyms not working after DB import between environments

### ISSUE THREAD

**Issue by DavidDRea** [humanmade/altis-enhanced-search#181]
After importing our production DB into our staging environment, indexing fails until we re-add synonyms in the manual entry meta box.

The same synonyms were configured on both the staging and production environments and after the DB import the correct synonyms were present in the manual entry meta box with the status 'active'.

However, we run into the error in the screenshot below.

![image](https://user-images.githubusercontent.com/26504442/113707919-7f6ec400-96d8-11eb-90c5-ef3d0ce97127.png)

This also happens when setting up a new local environment with a new DB import.

Steps to reproduce:
1. Import DB from one environment to another.
2. Initiate an elasticpress index.

**Comment by roborourke** [comment]
@DavidDRea apologies for the delay fixing this. I need to double check this in a cloud environment then I'll backport the fix and cut some patch releases.
