### ISSUE TITLE
The autosuggest configuration option does nothing

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-enhanced-search#184]
Steps to reproduce:

1. [As per the documentation](https://www.altis-dxp.com/resources/developer-docs/search/#search-form-auto-suggest), enable autosuggest in composer.json:

       "modules": {
           "search": {
               "autosuggest": true
           }
       }

2. Publish a page containing a search block
3. Type into the search input and observe that nothing happens

Checking the Network tab of the developer tools I can see that no Ajax requests are being made as I type. Reindexing the site has no effect.

I've also added a search input to the template using `get_search_form()` and this form does not get autosuggest functionality either.

**Comment by noeltock** [comment]
There's a client need/impact here, what is the scale of the issue to fix? Thank you 🙏

**Comment by roborourke** [comment]
Can you confirm the theme has no custom search form template?

**Comment by johnbillion** [comment]
Confirmed. I tested it with Twenty Twenty.

I can't see any JavaScript that gets enqueued that provides the autosuggest functionality.

**Comment by rmccue** [comment]
Looking into this now. Appears to be an issue with how we're overriding EP's settings.

**Comment by roborourke** [comment]
Specifically this code wasn't carried over from Enterprise Kit when I thought it was, I'll resolve and backport the fix later today https://github.com/humanmade/hm-platform/blob/beta/includes/settings.php#L111-L183

**Comment by rmccue** [comment]
The autosuggest feature's `get_settings()` is returning false, which causes the scripts/etc to never be enqueued. The code @roborourke outlines above should work, but we can also just define `EP_AUTOSUGGEST_ENDPOINT` instead. It will also need that latter part for the routing too.

(Ideally, EP would actually have a filter specifically for the endpoint, which they could also be use for the EP.io integration which is currently hardcoded.)

**Comment by johnbillion** [comment]
Thanks, tested locally and working nicely.
