### ISSUE TITLE
Autosuggest endpoint only works on main site on the network

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-enhanced-search#212]
Following on from #184. The autosuggest feature does not work on subdirectory sites on the network because the `/autosuggest` endpoint returns a 404

Steps to reproduce:

1. Enable `autosuggest` in the search config:

       "modules": {
           "search": {
               "autosuggest": true
           }
       }
2. Create a new site on the network, eg `example.com/site1`
3. Add a search form to a page
4. Try searching in the form and observe there are no autosuggest results

The problem is the `example.com/site1/autosuggest` endpoint returns a 404.

**Comment by miteshpandey** [comment]
Thanks for creating the issue @johnbillion. We're launching Wuest Partner website by end of May, and this issue has an impact on the final deliverables promised to the client. Can we consider this high priority please? 🙏

**Comment by roborourke** [comment]
Pull request up at #213 - cc @miteshpandey

**Comment by roborourke** [comment]
Fix released in 5.0.7, 6.0.5 and 7.0.1 of the search module
