### ISSUE TITLE
Attachment search does not find partial matches

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-enhanced-search#217]
Steps to reproduce:

1. Upload a file to your media library
2. From the Media screen, perform a search for part of the name of the file you uploaded, eg:
   - Upload a file called `foo_bar` and then search for `foo`
   - Upload a file called `john` and then search for `joh`
3. Observe there are no results

Partial matches work as expected when searching posts.

Partial matches for attachment names work as expected in vanilla WordPress.

Reported by a client who uploaded a file called `publication_202101-Immobilienmarktschweiz` and is unable to find the file by searching for `publication`.

**Comment by roborourke** [comment]
Looks like currently only the attachment title is included in the edge ngram search (matches returned based on every 3 characters).

You can set the `ep_integrate` query var to false for media searches in the meantime. Alternatively if including the post slug is enough you could use the following filter:

```php
add_filter( 'altis.search.autosuggest_post_fields', function ( $fields ) {
  $fields[] = 'post_name';
  return $fields;
} );
```

It would be nicer to index the file name specifically and use that as an autosuggest option I think.

Not strictly a bug, but unexpected.

**Comment by johnbillion** [comment]
When you upload a file, the filename is used to populate the title. You're right that the title is included in the search but it doesn't match in the same way that a post title does.

Given a post with a title of `foo_bar`, searching for `foo` will find the post. Given an attachment with the same title, the same search will not find that attachment. On a vanilla WP site the attachment will be found.

**Comment by roborourke** [comment]
Hmm, what you describe there works on the media search for me. Titles are matched even by 3 character searches. Elasticsearch works very differently to the vanilla WP SQL search so some differences are to be expected.

Which version of Altis and the search module is this with?

**Comment by johnbillion** [comment]
Altis v6 with Enhanced Search 6.0.5.

**Comment by miteshpandey** [comment]
@johnbillion @roborourke : Thanks for reviewing this issue. How're we taking this ahead? Is this something we can fix?

**Comment by roborourke** [comment]
You’ll have to use the docs and tools available to you to resolve it for now, happy for a solution to be contributed upstream too. I can’t make any promises about when this would be included in a product sprint. Additionally any solution might not be backported right now as it would likely involve a breaking change to the search mapping and require reindexing

**Comment by rmccue** [comment]
Sounds like we could not replicate, closing out.
