### ISSUE TITLE
Fix failure to remove/clear Elastic packages

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-enhanced-search#289]
Steps to reproduce:
1. Go to Search config admin page
2. Add uploaded or manual packages to any of the three package types ( synonyms, stopwords, user dictionary )
3. Save
4. Try removing/clearing the added package.

Expected: the package is cleared/removed
Actual: the package is not cleared/removed

**Comment by garethwelton** [comment]
Hei @shadyvb we don't tend to put story point values onto bugs, I'll add some comments to this is the playbook if not already meantioned.

**Comment by roborourke** [comment]
Fixed by #294
