### ISSUE TITLE
Install ElasticPress via composer

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-enhanced-search#29]
Currently we inline elasticpress, because there's no built-version on composer. We could do with getting that set up. We might need to fork ElasticPress and push it to our own composer package.

**Comment by JayWood** [comment]
Hello @joehoyle have you considered using WPackagist in the interim? https://wpackagist.org/

I use it for plugins which don't have a packagist repo already, but do exist in the WordPress repository.

**Comment by rmccue** [comment]
We ended up forking and publishing: https://github.com/humanmade/ElasticPress

We made a choice not to use WPackagist so we're not relying on a third-party Composer repository for our core infrastructure, as it requires special setup for all users.

**Comment by rmccue** [comment]
I *meant* to say, we ended up forking, we just need to also publish. 🤦‍♂

**Comment by joehoyle** [comment]
It's actually not possible to use wppackagist as a dep, as that requires the root project add wppackagist as a repo. Dependencies (like this composer package) can not define repositories, it's a root only thing.

**Comment by joehoyle** [comment]
This is now done
