### ISSUE TITLE
Support for Japanese

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-enhanced-search#32]
In https://github.com/humanmade/platform-dev/issues/373 around Slack Chat https://hmn.slack.com/archives/C3CKS8LLR/p1560848386374400 we have been investigating support for Japanese.

To anyone like me who had no idea how Japanese "works" here's a run down of the situation.

With the current ElasticPress config, we are setting the [EP language](https://github.com/humanmade/altis-enhanced-search/blob/master/inc/namespace.php#L356) to `cjk`. First problem: this breaks ElasticSearch, because the `ep_analyzer_language` filter is used for both the [analyzer](https://github.com/10up/ElasticPress/blob/b3d96a72dd54db1def357d6c0f093a2a182b6e06/includes/mappings/post/pre-5-0.php#L20) and in [a filter](https://github.com/10up/ElasticPress/blob/b3d96a72dd54db1def357d6c0f093a2a182b6e06/includes/mappings/post/pre-5-0.php#L45). Because `cjk` doesn't provide a stemmer, this breaks queries.

Anyway, `cjk` is only part of the issue. The changes needed to the index setting is much larger than just changing the default tokenizer's language.

So, a primer on Japanese as to why this doesn't work out of the box with ElasticPress: Japanese, for one, doesn't have a standard word separator like the SPACE in latin languages. This means off the bat there's basically no useful tokenizing of words. Also, Japanese has 4 charsets / alphabets (sorry for the lay understanding to anyone who speaks Japanese!), so there's no awareness of this from Elasticsearch out of the box.

To contend with the large language differences, there's as Elasticsearch plugin called [Kuromoji](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-kuromoji.html) which we can use. This provides better analysers and tokenizers for Japanese. To use those though, we basically need to roll out own index settings for Japanese instead of the [EP index file](https://github.com/10up/ElasticPress/blob/b3d96a72dd54db1def357d6c0f093a2a182b6e06/includes/mappings/post/pre-5-0.php#L45).

Using an index file more along the lines of :

```
"analysis" => [
			"filter" => [
			  "kuromoji_rf" => [
				"type" => "kuromoji_readingform",
				"use_romaji" => "false"
			  ]
			],
			"tokenizer" => [
			  "kuromoji" => [
				"type" => "kuromoji_tokenizer"
			  ]
			],
			"analyzer" => [
			  "default" => [
				"type" => "custom",
				"tokenizer" => "kuromoji",
				"filter" => [
				  "kuromoji_rf"
				]
			  ]
			]
		  ]
```

So, clearly that's more than setting the EP lang filter.

Beyond there there are however, other problems. Because JA doesn't have a standard separator, the way word tokenization is done is from a known dictionary. That means searching for words in the JA dictionary now works with the above config. However, no non-dictionary words will work, like proper nouns. It's my understanding, for that reason it's common to use user defined dictionaries in Kuromoji that is populated with all the possible proper nouns that will exist in the content, so the tokenizer can correctly split up the words.

The issue there is that we don't have access to User Dictionaries on Altis Cloud. Apparently there's maybe a workaround with synonyms instead, which we need to test.

I tried setting up the above config, and it mostly worked, apart from proper nouns. However, really this needs someone who speaks Japanese to take it from here, to verify both that cross-alphabet searching is doing what it should, and also verify that using ES synonyms as an appropriate workaround to the fact that we have no user dictionaries functionality.

**Comment by Kenshino** [comment]
Hello - can we look at this again soon?

1. The last time we talked to AWS about the user_dictionary support for kuromoji was about a year ago. Can we check in and see if anything's changed? - @Japh 
2. I've got two Japanese sites, PlayStation JP and FujiTV that I eventually think would benefit from Elasticsearch.

PlayStation seems slightly close https://github.com/humanmade/playstation/issues/1330 - if SIEA turns on Elasticsearch and uses it to performance advantages - I'd like to see SIEJ do the same.

**Comment by joehoyle** [comment]
This could be a good candidate for upcoming available time we have @roborourke / @rmccue  / @elodiebouneau

**Comment by joehoyle** [comment]
I see AWS now supports uploading dictionaries and the like, see https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/custom-packages.html

**Comment by roborourke** [comment]
Work under way here #74 - this solves the initial problem regarding the kuromoji analyser but not user dictionaries. I think we should get that PR in for v4.

User dictionary is a bit harder to do due to supporting both local set ups and production.

**Comment by roborourke** [comment]
Added in #76 🚀

**Comment by roborourke** [comment]
Note this will be released with v5 beta 1 within the next week
