### ISSUE TITLE
ES goes out of sync if deleting AND adding/updating content as part of the same thread

### ISSUE THREAD

**Issue by tcrsavage** [humanmade/altis-enhanced-search#372]
Steps to reproduce:

Add a post, then delete a post in the same php thread
See the added post is not synced to the ES server

EP sync manager currently deletes the sync queue without processing if a post is deleted
https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/SyncManager.php#L210

**Comment by tcrsavage** [comment]
Probably needs resolving on the EP side

**Comment by tcrsavage** [comment]
Issue created on EP side https://github.com/10up/ElasticPress/issues/2568

**Comment by roborourke** [comment]
Man, thanks for figuring that out. Super hard to diagnose but explains the sporadic nature of the problem. Will see if the fix can be backported, cc @shadyvb

**Comment by roborourke** [comment]
Resolved in Altis v11+ now with EP v4
