### ISSUE TITLE
SPIKE: ElasticPress 4.0 update

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-enhanced-search#389]
ElasticPress v4.0 is released, we need to update for compatibility with WP 5.9.

The version requires a full-reindex, and contains a new search algorithm that needs to be checked and possibly adjusted by Altis, and a new feature called instant results which apparently bypasses WP queries and queries ES directly need to examine that closely.

Ref: https://github.com/10up/ElasticPress/releases/tag/4.0.0 , https://10up.com/plugins/elasticpress/

Due to the unknowns included, this is created as a spike.

Timebox: 3 days

**Comment by shadyvb** [comment]
### Highlights:

> Note that ElasticPress 4.0.0 release removes built assets from the develop branch, replaced master with trunk, added a ZIP with the plugin and its built assets in the GitHub Releases page, and included a build script should you want to build assets from a branch. As such, please plan to update any references you have from master to trunk or to GitHub Releases depending on whether you require built assets or not. (See changes in #2622.)

Will see if that affects our use.

> Instant Results. Props @JakePT, @felipeelia, and Pratheep Chandrasekhar via #2481 and #2500.

Requires a reindex to activate, hits ES directly rather than WP_Query-then-ES. Bit scary given possible customizations in WP_Query calls (filters).

> New default search algorithm prioritizing exact matches, matches in the same field, then matches across different fields. Props @brandwaffle and @felipeelia via #2498.

Need to figure out a way to use the current one, and let projects opt-in new algo.

> Dynamic bulk requests limits. Instead of sending only one request per document batch, send several adjusting their sizes based on the Elasticsearch response. Props @felipeelia, @dinhtungdu, @brandwaffle, and @Rahmon via #2585.

Yay! :party: That'll make quite some difference, I hope.

> Sync page and code responsible for indexing. Props @helen, @felipeelia, @Rahmon, @mckdemps, @tott, and Pratheep Chandrasekhar via #1835, #2448, and #2501.

Dashboard page shows progress of CLI index processes. (but we disable those pages anyways)

> PHPUnit Tests and WordPress 5.9 compatibility. Props @felipeelia via #2569.

That's the goal!

> Posts insertion and deletion in the same thread. Props @felipeelia and @tcrsavage via #2575.

Tackles the long-standing support ticket around that bug.

> New sync code and the upper-limit-object-id and lower-limit-object-id parameters in WP-CLI command. Props @felipeelia via #2634.

Possibly making it easier to debug index issues by referencing a range of IDs to index.

### Actions

- Notification about the need to reindex after update, log to release notes. (irrelative to instant results).
- Default search algo override, make it opt-in.
- Log highlights from above into the release notes.

**Comment by shadyvb** [comment]
Just realized the unintentional pings :facepalm:, apologies to all.

**Comment by felipeelia** [comment]
No problems, @shadyvb. Actually, I think I can help with some additional info:

### Instant Results
The call made directly to Elasticsearch is based on a query template that is generated by a WP_Query [here](https://github.com/10up/ElasticPress/blob/4.0.1/includes/classes/Feature/InstantResults/InstantResults.php#L368). Although it goes directly to Elasticsearch, it will use an API format, that can be seen in this [PHP proxy](https://github.com/10up/elasticpress-proxy).

### Search algorithm
It is possible to use the previous version using: `add_filter( 'ep_search_algorithm_version', function() { return '3.5'; } );`

Let us know if you have any questions :)

**Comment by shadyvb** [comment]
Thanks Felipe! Appreciated!

**Comment by roborourke** [comment]
> > New default search algorithm prioritizing exact matches, matches in the same field, then matches across different fields.

> Need to figure out a way to use the current one, and let projects opt-in new algo.

I think it's ok to switch to the new algo in a new major version of Altis but we may need to document how to use the older versions if desired.

Anyone using advanced mode (ES's simple_query_string feature) in Altis won't be affected.

I'll check if the terms & user search algos were updated too, I think only the post search algo was updated since EP 3.5.

I'll close this one out and cross reference from the v11 release issue here humanmade/product-dev#969
