### ISSUE TITLE
Update ElasticPress v4.2

### ISSUE THREAD

**Issue by robindevitt** [humanmade/altis-enhanced-search#413]
ElasticPress 4.2 is released, so we need to update the package.

Two main changes that we're eyeing for the update:

- Reverting back the change to manually include the files in our repo, and use the composer package directly as we did before the change, as the package release process has been fixed to include assets as it used to. See https://github.com/10up/ElasticPress/pull/2799
- There was a bug that prevented indexing specific sites, where `--url` was ignored, that has been fixed as well. See https://github.com/10up/ElasticPress/issues/2766

Acceptance criteria:

- [ ] ElasticPress packages is used, and its files that were manually added are removed.
- [ ] Basic ElasticPress / Search functionalities are tested, both the manual and the automated parts as per our QA process

**Comment by shadyvb** [comment]
Worth noting that the installation process is now fixed, so we will want to go back to using the composer dependency. See https://github.com/10up/ElasticPress/pull/2799

**Comment by roborourke** [comment]
Is that from 4.2 onwards? Agree that’s something we need to do

**Comment by veselala** [comment]
@shadyvb please update the ticket with the additional info dat you've provided on our refinement

**Comment by veselala** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mercury-6284e0bfb386b00d11981426/issues/humanmade/altis-enhanced-search/413?planning-poker) with ZenHub @robindevitt @roborourke @shadyvb

**Comment by roborourke** [comment]
We need to pay close attention to whether reindexing is required as the ask here is to make an exception to normal semver practices - in some cases EP requires reindexing on a minor release.

**Comment by johnbillion** [comment]
The EP release notes don't mention requiring a reindex but if the current index is incomplete due to the `--url` flag bug then the site might need a reindex anyway.

**Comment by stuartshields** [comment]
@johnbillion From what I've seen it doesn't require a complete reindex after the fix is applied. But I would also test first to make sure.

**Comment by stuartshields** [comment]
Just adding a note here for this issue: 4.2.1 is now released and looks to fix:
> Fatal error related to WP-CLI timers on long-running syncs

Might be worthy of going to this version instead.

**Comment by stuartshields** [comment]
@veselala pinging you here as I am not sure where to ask the question.

Over the past 3 days we've had to wget the 4.2.1.zip onto our clients environments to fix indexing issues. This is around the `--url` flag, while this is a temp work around for us. I am wondering if there is anyway I can get this pushed up to be merged in sooner?

Thank you.

**Comment by roborourke** [comment]
@stuartshields I don’t see an associated PR so there’s nothing to merge right now

**Comment by stuartshields** [comment]
@roborourke I don't understand? A PR from this repo? Correct nothing exists, yet. However my comment above (sorry for not being clearer) is in reference to https://github.com/10up/ElasticPress/tree/4.2.1

**Comment by ivankristianto** [comment]
We hit our head couple times due to this bug in our project. Upgrading to 4.2.1 in the current codebase solves it. Can we separate this issue into 2 steps? first immediate thing is to upgrade the EP in the current codebase. second to reverting back as composer package.

**Comment by kovshenin** [comment]
Subscribing myself to this issue to track for v12.

**Comment by shadyvb** [comment]
Worth noting that 4.2.2 has been released with a fix for composer 2 compat.
