### ISSUE TITLE
Add ElasticPress debug bar

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-enhanced-search#55]
Query Monitor supports debug bar addons and 10up have this extension https://github.com/10up/debug-bar-elasticpress

Seems like it'd be really useful as debugging & profiling ElasticSearch can be painful at the best of times.

Acceptance criteria:

- [x] Plugin added to exclude list in humanmade/altis-core
- [x] Package `10up/debug-bar-elasticpress` is required in this module's `composer.json` at a fixed version (latest available)
- [x] Plugin is loaded when `Altis\get_config()['modules']['dev-tools']['query-monitor']` is `true`

**UPDATE**
After a discussion and the fact that we need to fix a lot of small things. We've decided to fork the plugin and fix it ourselves.

- fork the repo
- update the name in composer.json to be under the humanmade namespace
- fix the assets URL code 
- update the CSS
- publish to packagist

**Comment by dashaluna** [comment]
<img width="1201" alt="Screenshot 2020-02-13 12 00 56" src="https://user-images.githubusercontent.com/2185972/74433960-5bf41480-4e59-11ea-98ee-6d292173ba51.png">

**Comment by roborourke** [comment]
Cheers, can you double check it's working by going to the posts list page in the admin and doing a search? Then do a search on the front end. We _might_ need to do a bit of styling on this looking at the screenshot above.

Also if it's possible to remove the "Debug Bar: " text that'd be ace.

**Comment by dashaluna** [comment]
@roborourke also getting the following errors:

```
[13-Feb-2020 15:45:57 UTC] PHP Notice:  Style debug-bar-elasticpress error [altis.security.browser.invalid_path]: Path "https://altis-dasha-dev.local/vendor/10up/debug-bar-elasticpress/classes/../assets/css/main.css" for debug-bar-elasticpress is invalid in /chassis/vendor/altis/browser-security/inc/namespace.php on line 103
....
[13-Feb-2020 15:45:57 UTC] PHP  11. Altis\Security\Browser\generate_hash_for_style() /chassis/wordpress/wp-includes/class-wp-hook.php:290
```

```
[13-Feb-2020 15:45:57 UTC] PHP Notice:  Script debug-bar-elasticpress error [altis.security.browser.invalid_path]: Path "https://altis-dasha-dev.local/vendor/10up/debug-bar-elasticpress/classes/../assets/js/main.js" for debug-bar-elasticpress is invalid in /chassis/vendor/altis/browser-security/inc/namespace.php on line 125
....
[13-Feb-2020 15:45:57 UTC] PHP  13. Altis\Security\Browser\generate_hash_for_script() /chassis/wordpress/wp-includes/class-wp-hook.php:288
```

**Comment by dashaluna** [comment]
Admin search is working:
<img width="1677" alt="Screenshot 2020-02-13 16 12 11" src="https://user-images.githubusercontent.com/2185972/74454500-e64d7000-4e7b-11ea-8c57-18f6401a3284.png">

**Comment by roborourke** [comment]
Those warnings highlight an interesting problem when you take a shortcut for generating asset URLs, the problem is the '..' that the browser security plugin doesn't like. @rmccue thinking we could use a filter to just correct any relative paths in URLs like this to absolute URLs.

@dashaluna shame about the styling, I think we definitely want to improve that. It might be related to the above issue though. Going to check quickly

**Comment by dashaluna** [comment]
Searching on front end for the post name I know exists returns no results, and QM info isn't updated (from the previous query).

**Comment by dashaluna** [comment]
> Those warnings highlight an interesting problem when you take a shortcut for generating asset URLs, the problem is the '..' that the browser security plugin doesn't like.

I wonder if it's worth contacting 10up and asking for making the URL absolute?

**Comment by roborourke** [comment]
We could just make a PR to their repo I think but this is an issue that could come up in more places.

**Comment by roborourke** [comment]
Opened https://github.com/humanmade/altis-cms/pull/190 to fix those invalid path warnings
