### ISSUE TITLE
Update to ElasticPress v3

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-enhanced-search#77]
@joehoyle has the existing start of work for EP v3 at #35, but we don't have a corresponding issue for it.

A notable barrier to this, and why we've taken so long, is that the index names have changed (as noted in #35). We should work out an upgrade path.

**Comment by pdewouters** [comment]
The latest version `3.4.2` has a bug which causes an error in the WP admin, I made a PR to fix, https://github.com/10up/ElasticPress/pull/1829

**Comment by rmccue** [comment]
Just noting: we've completed the EP v3 migration work in #35, but there may be additional pieces to complete for v5 release. We'll split out any other issues as needed.
